USE [GBIY_DATACOLLECTION]
GO

/****** Object:  Table [dbo].[USERCHECKINS]    Script Date: 7.05.2017 18:08:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERCHECKINS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CHECKINID] [int] NULL,
	[TYPEID] [int] NULL,
	[POSTID] [int] NULL,
	[CHECKINDETAILS] [int] NULL,
 CONSTRAINT [PK_USERCHECKINS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


