USE [GBIY_DATACOLLECTION]
GO

/****** Object:  Table [dbo].[USERINFO]    Script Date: 7.05.2017 18:09:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERINFO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[SOCIALID] [nvarchar](100) NULL,
	[NAME] [nvarchar](100) NULL,
	[DESCRIPTION] [nvarchar](300) NULL,
	[EMAIL] [nvarchar](100) NULL,
	[FAVORITECOUNT] [int] NULL,
	[FOLLOWERCOUNT] [int] NULL,
	[FRIENDSCOUNT] [int] NULL,
	[LOCATION] [nvarchar](100) NULL,
	[UPDATEDDATE] [datetime] NULL,
	[PHOTOLINK] [nvarchar](500) NULL,
 CONSTRAINT [PK_USERINFO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


