USE [GBIY_DATACOLLECTION]
GO

/****** Object:  Table [dbo].[USERPOSTS]    Script Date: 7.05.2017 18:09:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERPOSTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [nvarchar](200) NULL,
	[POSTID] [nvarchar](200) NULL,
	[TYPEID] [int] NULL,
 CONSTRAINT [PK_USERPOSTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


