USE [GBIY_DATASET]
GO

/****** Object:  Table [dbo].[CATEGORY]    Script Date: 7.05.2017 18:10:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATEGORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](200) NULL,
	[PLURALNAME] [nvarchar](200) NULL,
	[SHORTNAME] [nvarchar](200) NULL,
	[ICONLINK] [nvarchar](500) NULL,
	[PARENTID] [int] NULL,
	[SWARMID] [nvarchar](200) NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


