USE [GBIY_DATASET]
GO

/****** Object:  Table [dbo].[CATEGORYPOINT]    Script Date: 7.05.2017 18:11:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATEGORYPOINT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORYID] [int] NULL,
	[POINT] [float] NULL,
 CONSTRAINT [PK_CATEGORYPOINT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


