USE [GBIY_DATASET]
GO

/****** Object:  Table [dbo].[CHECKIN]    Script Date: 7.05.2017 18:11:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHECKIN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PLACEID] [int] NULL,
	[POSTID] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[LIKECOUNT] [int] NULL,
	[WITHCOUNT] [nchar](10) NULL,
	[SCORE] [nchar](10) NULL,
	[SHOUT] [nvarchar](300) NULL,
 CONSTRAINT [PK_CHECKIN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


