USE [GBIY_DATASET]
GO

/****** Object:  Table [dbo].[PLACE]    Script Date: 7.05.2017 18:12:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PLACE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SWARMID] [nvarchar](100) NULL,
	[NAME] [nvarchar](200) NULL,
	[CITY] [nvarchar](200) NULL,
	[COUNTRY] [nvarchar](200) NULL,
	[ADDRESS] [text] NULL,
	[LAT] [nvarchar](50) NULL,
	[LNG] [nvarchar](50) NULL,
	[CHECKINCOUNT] [int] NULL,
	[TIPCOUNT] [int] NULL,
	[USERSCOUNT] [int] NULL,
 CONSTRAINT [PK_PLACE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


