USE [GBIY_DATASET]
GO

/****** Object:  Table [dbo].[PLACECATEGORY]    Script Date: 7.05.2017 18:12:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PLACECATEGORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PLACEID] [int] NULL,
	[CATEGORYID] [int] NULL,
 CONSTRAINT [PK_PLACECATEGORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


