USE [GBIY_DATASET]
GO

/****** Object:  Table [dbo].[TRIPADVISORPLACES]    Script Date: 7.05.2017 18:13:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TRIPADVISORPLACES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PLACENAME] [nvarchar](200) NULL,
	[LOCATION] [nvarchar](200) NULL,
 CONSTRAINT [PK_TRIPADVISORPLACES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


