USE [GBIY_IDP]
GO

/****** Object:  Table [dbo].[USERINFORMATION]    Script Date: 7.05.2017 18:18:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERINFORMATION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[NAME] [nvarchar](100) NULL,
	[SURNAME] [nvarchar](100) NULL,
	[CITY] [nvarchar](100) NULL,
	[COUNTRY] [nvarchar](100) NULL,
	[BIRTHDATE] [date] NULL,
 CONSTRAINT [PK_USERINFORMATION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


