USE [GBIY_IDP]
GO

/****** Object:  Table [dbo].[USERQUESTIONANSWERS]    Script Date: 7.05.2017 18:18:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERQUESTIONANSWERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[QUESTIONID] [int] NULL,
	[ANSWER] [tinyint] NULL,
 CONSTRAINT [PK_USERQUESTIONANSWERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


