USE [GBIY_IDP]
GO

/****** Object:  Table [dbo].[USERSWARMTOKENS]    Script Date: 7.05.2017 18:19:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERSWARMTOKENS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[SWARMTOKEN] [text] NULL,
	[UPDATEDDATE] [date] NULL,
	[EXPIRED] [bit] NULL,
 CONSTRAINT [PK_USERSWARMTOKENS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


